### ISSUE TITLE
demo siamapn++

### ISSUE THREAD

**Issue by mark-91** [vision4robotics/SiamAPN#12]
i try run demo and i have this problem>>> or if someone give some tutorial to use siamapn in my project  
python3 demo_apn++.py 
Traceback (most recent call last):
  File "demo_apn++.py", line 99, in <module>
    main()
  File "demo_apn++.py", line 68, in main
    model = load_pretrain(model, args.snapshot).eval().to(device)
  File "../pysot/utils/model_load.py", line 51, in load_pretrain
    map_location=lambda storage, loc: storage.cuda(device))
  File "/home/ai/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './snapshot/general_model.pth'

**Comment by vision4robotics** [comment]
Please download our pre-trained model and put it into ./snapshot
